### PR TITLE
Add several new contexts.

### PR DESCRIPTION
**Pull request by mattcollier**
Waiting on releases of all the new context modules.

### CODE REVIEW

**Review by dmitrizagidulin — APPROVED** [review]
:+1:

**Review by dlongley — APPROVED** [review]
LGTM

**Review by JSAssassin — APPROVED** [review]

**Comment by dmitrizagidulin** [comment]
@mattcollier @JSAssassin - ok, the 4 new contexts have now been pubished to npm at 1.0

- `aes-key-wrapping-2019-context`
- `sha256-hmac-key-2019-context`.
- `webkms-context`.
- `zcap-context`.

**Comment by dmitrizagidulin** [comment]
@mattcollier - I updated the deps and test deps to the published npm packages of the contexts.

**Pull request merged**
